### ISSUE TITLE
Installation fails on Magento 2.0.4

### ISSUE THREAD

**Issue by grasdaggel** [shockwavemk/magento2-module-mail-smtp#3]
The module throws an error on accessing the respecive configure-tab in the backend. 

```
Class Shockwavemk\Mail\Smtp\Model\Config\Source\Smtp\Authentication does not exist
#0 /home/atroposstage/public_html/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Shockwavemk\\Mai...')
#1 /home/atroposstage/public_html/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Shockwavemk\\Mai...')
#2 /home/atroposstage/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Shockwavemk\\Mai...')
#3 /home/atroposstage/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(71): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Shockwavemk\\Mai...')
#4 /home/atroposstage/public_html/vendor/magento/module-config/Model/Config/SourceFactory.php(33): Magento\Framework\ObjectManager\ObjectManager->get('Shockwavemk\\Mai...')
#5 /home/atroposstage/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(425): Magento\Config\Model\Config\SourceFactory->create('Shockwavemk\\Mai...')
#6 /home/atroposstage/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(361): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel('Shockwavemk\\Mai...')
#7 /home/atroposstage/public_html/var/generation/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(310): Magento\Config\Model\Config\Structure\Element\Field->getOptions()
#8 /home/atroposstage/public_html/vendor/magento/module-config/Block/System/Config/Form.php(379): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->getOptions()
#9 /home/atroposstage/public_html/vendor/magento/module-config/Block/System/Config/Form.php(284): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'system/smtp/aut...', '', '')
#10 /home/atroposstage/public_html/vendor/magento/module-config/Block/System/Config/Form.php(224): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
```

**Comment by shockwavemk** [comment]
I will look into this issue
